name = "teaspoon"
main = "src/worker.js"
compatibility_date = "2024-09-23"

[build]
command = "npm install && npm run build"

[vars]
ENTRIES_PAGE_SIZE = 4
CONTACT_EMAIL = "teaspooncz@gmail.com"

[assets]
directory = "_site"
binding = "ASSETS"

[observability.logs]
enabled = true
invocation_logs = true

[[d1_databases]]
binding = "DB"
database_name = "teaspoon-forms"
database_id = "5339935f-7eca-4031-8d12-d527c3734dbb"
