name = "teaspoon"
main = "src/worker.js"
compatibility_date = "2024-09-23"

[assets]
directory = "web"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "teaspoon-forms"
database_id = "5339935f-7eca-4031-8d12-d527c3734dbb"
